### PR TITLE
Updated node packages versions

### PR DESCRIPTION
**Pull request by troccoli**
This PR just updates the versions of all the packages to the latest available (at the time of writing).

I was trying to install the package in a new project and I had a lot of vulnerabilities reported by `npm`. So I decided to submit a PR to update the dependencies.

Note that I have not updated the version in `packages.json` mainly because I don't know if this should be a new major version, `1.0.0`, or a new minor version, `0.3.0`. I cannot be sure but I think there may be breaking changes in the new versions of the packages.

A note on Cypress. I have updated its version too, although I'm not really sure why it's a dependency in the first place.

### CODE REVIEW

**Comment by NoelDeMartin** [comment]
@troccoli Hey, is there any reason why you closed this PR? I saw it and wanted to take a closer look, is it no longer necessary?

**Comment by troccoli** [comment]
Hi, sorry about that, I should have left a comment.

The reason I closed it is that I had all sorts of issues running `npm run build`. I thought then that upgrading the packages wasn't that straightforward.

**Comment by NoelDeMartin** [comment]
@troccoli ok, thanks for opening the PR anyways. If the package is not working with the latest versions of Laravel/Cypress please open an issue and I can take a look.

**Comment by troccoli** [comment]
I will. I was trying to be a bit more proactive.

Thanks

**Pull request closed without merging**
